apiVersion: v1
kind: Pod
metadata:
  name: pytest-ssp-feature
spec:
  imagePullSecrets:
    - name: vungleregistrykey
  containers:
    - name: pytest-ssp-feature
      image: sqli0189/jnlp-agent-pytest:latest
      imagePullPolicy: Always
      env:
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0"
      resources:
        requests:
          memory: "2048Mi"
          cpu: "1000m"
        limits:
          memory: "2048Mi"
          cpu: "1000m"
      command:
      - cat
      tty: true