# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configExtension.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63onfigExtension.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd4\x01\n\x0f\x43onfigExtension\x12!\n\x0b\x65xperiments\x18\x01 \x01(\x0b\x32\x0c.Experiments\x12\x11\n\tipaddress\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x64_network_ids\x18\x03 \x03(\t\x12\'\n\x03lmt\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x17\n\x06\x64\x65vice\x18\x05 \x01(\x0b\x32\x07.Device\x12\x31\n\rdisable_ad_id\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\"\x85\x01\n\x0b\x45xperiments\x12+\n\x08\x63\x66g_exps\x18\x01 \x03(\x0b\x32\x19.Experiments.CfgExpsEntry\x12\x19\n\x04\x65xps\x18\x02 \x03(\x0b\x32\x0b.Experiment\x1a.\n\x0c\x43\x66gExpsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"W\n\nExperiment\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x62ucket_name\x18\x02 \x01(\t\x12&\n\x08strategy\x18\x03 \x01(\x0e\x32\x14.EXPERIMENT_STRATEGY\"\x90\x03\n\x06\x44\x65vice\x12\n\n\x02os\x18\x01 \x01(\t\x12\x0b\n\x03osv\x18\x02 \x01(\t\x12\x0c\n\x04make\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12\x1a\n\x12\x62rowser_user_agent\x18\x05 \x01(\t\x12\r\n\x05width\x18\x06 \x01(\x03\x12\x0e\n\x06height\x18\x07 \x01(\x03\x12-\n\x07\x63\x61rrier\x18\x0b \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\x0f\x63onnection_type\x18\x0c \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12<\n\x16\x63onnection_type_detail\x18\r \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x33\n\rbattery_level\x18\x0e \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12<\n\x17storage_bytes_available\x18\x0f \x01(\x0b\x32\x1b.google.protobuf.Int64Value*@\n\x13\x45XPERIMENT_STRATEGY\x12\n\n\x06RECORD\x10\x00\x12\t\n\x05\x41PPLY\x10\x01\x12\x12\n\x0eNOT_IN_TRAFFIC\x10\x02\x62\x06proto3')

_EXPERIMENT_STRATEGY = DESCRIPTOR.enum_types_by_name['EXPERIMENT_STRATEGY']
EXPERIMENT_STRATEGY = enum_type_wrapper.EnumTypeWrapper(_EXPERIMENT_STRATEGY)
RECORD = 0
APPLY = 1
NOT_IN_TRAFFIC = 2


_CONFIGEXTENSION = DESCRIPTOR.message_types_by_name['ConfigExtension']
_EXPERIMENTS = DESCRIPTOR.message_types_by_name['Experiments']
_EXPERIMENTS_CFGEXPSENTRY = _EXPERIMENTS.nested_types_by_name['CfgExpsEntry']
_EXPERIMENT = DESCRIPTOR.message_types_by_name['Experiment']
_DEVICE = DESCRIPTOR.message_types_by_name['Device']
ConfigExtension = _reflection.GeneratedProtocolMessageType('ConfigExtension', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGEXTENSION,
  '__module__' : 'configExtension_pb2'
  # @@protoc_insertion_point(class_scope:ConfigExtension)
  })
_sym_db.RegisterMessage(ConfigExtension)

Experiments = _reflection.GeneratedProtocolMessageType('Experiments', (_message.Message,), {

  'CfgExpsEntry' : _reflection.GeneratedProtocolMessageType('CfgExpsEntry', (_message.Message,), {
    'DESCRIPTOR' : _EXPERIMENTS_CFGEXPSENTRY,
    '__module__' : 'configExtension_pb2'
    # @@protoc_insertion_point(class_scope:Experiments.CfgExpsEntry)
    })
  ,
  'DESCRIPTOR' : _EXPERIMENTS,
  '__module__' : 'configExtension_pb2'
  # @@protoc_insertion_point(class_scope:Experiments)
  })
_sym_db.RegisterMessage(Experiments)
_sym_db.RegisterMessage(Experiments.CfgExpsEntry)

Experiment = _reflection.GeneratedProtocolMessageType('Experiment', (_message.Message,), {
  'DESCRIPTOR' : _EXPERIMENT,
  '__module__' : 'configExtension_pb2'
  # @@protoc_insertion_point(class_scope:Experiment)
  })
_sym_db.RegisterMessage(Experiment)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
  'DESCRIPTOR' : _DEVICE,
  '__module__' : 'configExtension_pb2'
  # @@protoc_insertion_point(class_scope:Device)
  })
_sym_db.RegisterMessage(Device)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXPERIMENTS_CFGEXPSENTRY._options = None
  _EXPERIMENTS_CFGEXPSENTRY._serialized_options = b'8\001'
  _EXPERIMENT_STRATEGY._serialized_start=900
  _EXPERIMENT_STRATEGY._serialized_end=964
  _CONFIGEXTENSION._serialized_start=58
  _CONFIGEXTENSION._serialized_end=270
  _EXPERIMENTS._serialized_start=273
  _EXPERIMENTS._serialized_end=406
  _EXPERIMENTS_CFGEXPSENTRY._serialized_start=360
  _EXPERIMENTS_CFGEXPSENTRY._serialized_end=406
  _EXPERIMENT._serialized_start=408
  _EXPERIMENT._serialized_end=495
  _DEVICE._serialized_start=498
  _DEVICE._serialized_end=898
# @@protoc_insertion_point(module_scope)
