apiVersion: v1
kind: Secret
metadata:
  name: github-repo-cred
  namespace: 57blocks
type: Opaque
data:
  repo-user: ZW1pbHktNTdibG9ja3M=
  repo-token: Z2hwX3JzY3FlbFJSQjNnOU1GdWl2ZHphY3QwRXdMNFZSZjFIUUJNeA==